networks:
  scorpio:

# https://docs.ddev.com/en/stable/users/extend/custom-docker-services/
services:
    scorpio:
        container_name: "ddev-${DDEV_SITENAME}-scorpio"
        hostname: scorpio.local
        image: scorpiobroker/all-in-one-runner:java-latest
        restart: "no"
        ports:
            - "9090"
        environment:
            - VIRTUAL_HOST=${DDEV_HOSTNAME}
            - HTTP_EXPOSE=9090:9999
            - DBHOST=scorpio-db
        depends_on:
            - "scorpio-db"
        networks:
            - default
            - scorpio
        platform: "linux/amd64"

    scorpio-db:
        container_name: "ddev-${DDEV_SITENAME}-scorpio-db"
        image: postgis/postgis
        environment:
            - POSTGRES_USER=ngb
            - POSTGRES_PASSWORD=ngb
            - POSTGRES_DB=ngb
        networks:
            - scorpio
        volumes:
            - ./data/scorpio-db:/var/lib/postgresql/data
        platform: "linux/amd64"
        # https://stackoverflow.com/a/58806511
        command: ["postgres", "-c", "log_statement=all"]
